### ISSUE TITLE
String format

### ISSUE THREAD

**Issue by namerci** [3breadt/dd-plist#24]
Hi!

I'm parsing binary plist and get something like that:

```
        <dict>
            <key>$class</key>
            <string>7d0ffffffe3</string>
            <key>NS.bytes</key>
            <data>
                9jz+91kt1WmqSyfQEvv/2eDtiF0=
            </data>
        </dict>
```

What is a `<string>` format?
`<data>`is a base64 format.

**Comment by 3breadt** [comment]
String is something hexadecimal. Without further context information this is not possible to answer.
