### ISSUE TITLE
Parsing "Simple String File Format"

### ISSUE THREAD

**Issue by jeremysears** [3breadt/dd-plist#29]
I'm parsing some InfoPlist.strings files that are in "simple string file format".  For example:

```
/* A human readable InfoPlist.strings in simple strings format */

/* The bundle name */
"CFBundleName" = "(Base) Name";
/* The bundle display name */
"CFBundleDisplayName" = "(Base) DisplayName";
/* The short version */
"CFBundleShortVersionString" = "(Base) ShortVersion";
```

This is basically an ASCII NSDictionary, with an implied open/close curly brace.  Is there any plan to support this?  Alternatively, can you suggest any way I could augment the parser to support this?  I'd be happy to submit a PR, if you can point me in the right direction.

The Simple Strings File Format is described here:
[https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/LoadingResources/Strings/Strings.html](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/LoadingResources/Strings/Strings.html)

**Comment by 3breadt** [comment]
I would not include support for .strings file in the property list library as it is a file format not related to property lists.

But you can use the ASCII property list parser to parse such files with ease. Please refer to the following example code for reading a strings file.

`Charset utf8 = Charset.forName("UTF-8");`
`byte[] stringFileContentRaw = Files.readAllBytes(Paths.get("somefilename.strings"));`
`String stringFileContent = new String(stringFileContentRaw, utf8);`
`String asciiPropertyList = "{" + stringFileContent + "}";`
`NSDictionary dict = (NSDictionary)ASCIIPropertyListParser.parse(asciiPropertyList.getBytes(utf8));`
