### ISSUE TITLE
Base64 Decoder Incorrectly Detects Data Value as Zip Data

### ISSUE THREAD

**Issue by jeremysears** [3breadt/dd-plist#31]
Hello, and thank you for maintaining this library.

I recently encountered an issue parsing a plist contained in an iOS app.  iOS creates a CodeResources file in XML Plist format, which has dictionary with an entry for each file contained in the app.  The keys are the names of the files, and the values are another dictionary with file hash data for the file.  For example:

	...
	<key>files2</key>
	<dict>
		...
		<key>Base.lproj/Main.storyboardc/MainController.nib</key>
		<dict>
			<key>hash</key>
			<data>
			H4su9pQU+nD/V4ppfPwJGSNcjv8=
			</data>
			<key>hash2</key>
			<data>
			8MhWcI9M79dqHp4tTbcUBwJCeu63sn/ekQKdGAVQLUM=
			</data>
		</dict> 
		...

The data element is parsed by the Base64 encoder included in the library, which attempts to detect whether the data is in gzip format, and if so, pipes the output through a GZipInputStream.  It detects whether the data is in gzip format by [checking to see if the first two bytes are equal to the gzip magic number](https://github.com/develar/dd-plist/blob/master/src/main/java/com/dd/plist/Base64.java#L1306).  Unfortunately, given that the hash data is effectively just a random byte array, there is a 1 in 2^16 chance that the first two bytes of the hash will happen to be equal to the gzip magic number.  The "H4su9pQU+nD/V4ppfPwJGSNcjv8=" hash value above exhibits that behavior.  The decoded hexdump of that byte array is

	1f 8b 2e f6 94 14 fa 70 ff 57 8a 69 7c fc 09 19
	23 5c 8e ff

As you can see, the first two bytes happen to be the little-endian representation of the gzip magic number: 0x8b1f.  However, this isn't actual zip data, and it results in the following error:

	java.util.zip.ZipException: Unsupported compression method
		at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:169)
		at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
		at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
		at com.dd.plist.Base64.decode(Base64.java:1315)
		at com.dd.plist.Base64.decode(Base64.java:1266)
		at com.dd.plist.NSData.<init>(NSData.java:60)
		at com.dd.plist.XMLPropertyListParser.parseObject(XMLPropertyListParser.java:224)
		at com.dd.plist.XMLPropertyListParser.parseObject(XMLPropertyListParser.java:203)
		at com.dd.plist.XMLPropertyListParser.parseObject(XMLPropertyListParser.java:203)
		at com.dd.plist.XMLPropertyListParser.parse(XMLPropertyListParser.java:181)
		at com.dd.plist.XMLPropertyListParser.parse(XMLPropertyListParser.java:142)
		at com.dd.plist.PropertyListParser.parse(PropertyListParser.java:242)
		at com.dd.plist.PropertyListParser.parse(PropertyListParser.java:219)

I'd like to be able to disable the automatic zip decoding of data values, but it's not possible via the current APIs.  I'd like to propose either disabling this behavior by default -- this is the default behavior for write, and should probably be symmetrical with read.  Alternatively, we could plumb in a way to disable this behavior by adding an overloaded version of the PropertyListParser.parse(...) methods and similarly the XXXPropertyListParser implementations and the NSData(String) constructor.  Yet another alternate implementation would be to do further examination of the byte array structure to determine if it contains a well formed zip header data, though this would only reduce the likelyhood of the issue.  If you would be willing to entertain any of these fixes, or suggest an alternate, I would be happy to submit a pull request with the implementation.

Thank you again for maintaining this library.  I'd be happy to lend a hand.

**Comment by jeremysears** [comment]
Here is a simple stripped down example that demonstrates the issue and can be used in unit tests.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>files2</key>
	<dict>
		<key>Base.lproj/Main.storyboardc/MainController.nib</key>
		<dict>
			<key>hash</key>
			<data>
			H4su9pQU+nD/V4ppfPwJGSNcjv8=
			</data>
			<key>hash2</key>
			<data>
			8MhWcI9M79dqHp4tTbcUBwJCeu63sn/ekQKdGAVQLUM=
			</data>
		</dict>
	</dict>
</dict>
</plist>

```

**Comment by 3breadt** [comment]
Thank you for the detailed report. This behavior is actually unintended. I disabled the automatic handling of (potential) GZIP data. 

Fixed in 7fa14da1c303d54f5993209cf260447b2fd2fec3.

**Comment by jeremysears** [comment]
Thank you very much for the quick patch!  Are there any plans to create a 1.19 release that would include this fix?  Thanks again for your help.

**Comment by 3breadt** [comment]
If no further issues come up in the next week I will create a release 1.19.
