### ISSUE TITLE
XMLPropertyListParser UnsupportedOperationException on Android

### ISSUE THREAD

**Issue by llooz** [3breadt/dd-plist#36]
With the version 1.19 i have this crash on Android:
>  Caused by: java.lang.UnsupportedOperationException: This parser does not support specification "Unknown" version "0.0"
                                                                                  at javax.xml.parsers.DocumentBuilderFactory.setXIncludeAware(DocumentBuilderFactory.java:471)
                                                                                  at com.dd.plist.XMLPropertyListParser.<clinit>(XMLPropertyListParser.java:67)

**Comment by farmerbb** [comment]
Also seeing this crash with version 1.19.

**Comment by farmerbb** [comment]
Also seeing this crash with versions 1.17, 1.18 and 1.19.  1.16 and earlier do not crash.

Looks like [Android's implementation of `setXIncludeAware()`](https://android.googlesource.com/platform/libcore/+/master/luni/src/main/java/javax/xml/parsers/DocumentBuilderFactory.java#470) will always throw an UnsupportedOperationException.  Removing the [call to `setXIncludeAware()`](https://github.com/3breadt/dd-plist/blob/master/src/main/java/com/dd/plist/XMLPropertyListParser.java#L67) should fix this crash.

**Comment by 3breadt** [comment]
Thank you for your report. This issue was been introduced by #26 and will be fixed in release 1.20.

**Comment by Goddchen** [comment]
Any news on how 1.20 will be released? dd-plist is not usable on Android as of now :/

**Comment by 3breadt** [comment]
@Goddchen Sorry for the delay, I released 1.20 now.

**Comment by Goddchen** [comment]
@3breadt wow thanks. Helped me a lot. For everyone else: what I did until right now is revert back to version 1.8 since this is the latest version available on Maven Central that works with Android.

Just tested 1.20, works perfectly! Good work!
