### ISSUE TITLE
UIDs are 64-bit numbers, their constructor should support numbers.

### ISSUE THREAD

**Issue by claunia** [3breadt/dd-plist#38]
As per
https://github.com/claunia/plist-cil/issues/3
I checked and that's what Apple's code does.
tl;dr: it takes a 64-bit number and stores it in 1, 2, 4 or 8 big-endian bytes depending on its value.

So creating an UID object from a number (byte/int/long) should be supported.
Here's my code:
https://github.com/claunia/plist-cil/commit/1979dab8fa8616575c647832112f594ec8dd06a6

**Comment by abdulaziz52** [comment]
Hi
