### ISSUE TITLE
XMLPropertyListParser's getDocBuilder method need not be synchronized

### ISSUE THREAD

**Issue by mailniranjan** [3breadt/dd-plist#39]
https://github.com/3breadt/dd-plist/blob/master/src/main/java/com/dd/plist/XMLPropertyListParser.java#L91 is a synchronized method and is causing performance problems in our peak load testing.

This method was synchronized from the first commit. (https://github.com/3breadt/dd-plist/commit/ad6ecc42bdae884c608811820903ab1b31a8ae72#diff-2c27b48e0134dc885800b0487859238aR71). I can understand that there are initializing the docBuilderFactory variable lazily so that was the reason that method was synchronized.

With the current code, (https://github.com/3breadt/dd-plist/blob/master/src/main/java/com/dd/plist/XMLPropertyListParser.java#L49), the factory is initialized eagerly. So, the method need not be synchronized now.

**Comment by 3breadt** [comment]
Thanks for your contribution.
