### ISSUE TITLE
Various undeclared exceptions with fuzzed input

### ISSUE THREAD

**Issue by theobisproject** [3breadt/dd-plist#73]
I started fuzzing this library with https://github.com/CodeIntelligenceTesting/jazzer after originally fuzzing another library and seeing there some crashed in this projects code.

To reproduce the errors use the `PropertyListParser.parse` method.

The fuzzing treats all non declared exceptions as failure.  
One file triggers the exception in `BinaryPropertyListParser.doParse`. Since normally no one would catch this exception I included it since changing this to a `PropertyListFormatException` could be reasonable.

[plist-crash.zip](https://github.com/3breadt/dd-plist/files/9954842/plist-crash.zip)

**Comment by 3breadt** [comment]
Thank you for these findings. The detected issues have been fixed, i.e. proper exceptions are now thrown.

**Comment by theobisproject** [comment]
Thanks for the quick fix. I will continue fuzzing and see if more errors can be found.
