### ISSUE TITLE
Various undeclared exceptions with fuzzed input - Part 2

### ISSUE THREAD

**Issue by theobisproject** [3breadt/dd-plist#74]
Follow up run with the changes for #73. I split up the files into folders by exception type since there are more files this time due to a longer run.

The slow folder contains files which can take up to several minutes before crashing. One file will not crash. Presumably those files trigger a long running loop somewhere.

[plist-crash2.zip](https://github.com/3breadt/dd-plist/files/9964933/plist-crash2.zip)

**Comment by 3breadt** [comment]
The files from the slow folder now either throw an exception, or finish parsing successfully. Those who parse correctly are slow because they contain large NSSets containing millions of references to the same object. Parsing in this and similar cases has been optimized.
