### ISSUE TITLE
NSNumber parser fails for "+infinity" and "-infinity"

### ISSUE THREAD

**Issue by pfn-shi** [3breadt/dd-plist#83]
Using version 1.26, downloaded from Maven Central.

The NSNumber parser throws an exception when it encounters the values "+infinity" or "-infinity". This can be verified with the following code snippet:

```    
public static void main(String[] args) {
    var a = new NSNumber("3");
    try {
        var b = new NSNumber("+infinity");
    } catch (Exception e) {
        System.out.println(e);
    }
    try {
        var c = new NSNumber("-infinity");
    } catch (Exception e) {
        System.out.println(e);
    }
}
```

Output:

```
java.lang.IllegalArgumentException: The given string neither represents a double, an int nor a boolean value.
java.lang.IllegalArgumentException: The given string neither represents a double, an int nor a boolean value.
```

This causes `XMLPropertyListParser.parse(...)` to fail when the input contains either `<real>+infinity</real>` or `<real>-infinity</real>` but I believe both of these are valid values.

**Comment by 3breadt** [comment]
Thank you for your report. The issue has been fixed and the fix will be included in the next release.
