### ISSUE TITLE
ParseException errorOffset from ASCIIPropertyListParser::parseQuotedString is offset by the length of the quoted string

### ISSUE THREAD

**Issue by jabagawee** [3breadt/dd-plist#88]
**Reproduction steps:**
Purposefully try to parse a badly quoted string. For example:
```
{
    "Hello" = "Worl\d";
}
```

**Expected results:**
The `ParseException` should point `errorOffset` to the `\d`, implied by the expression `this.index + ex.getErrorOffset()` at https://github.com/3breadt/dd-plist/blob/a68d259916108e498164b82795e241bfd08e07a1/src/main/java/com/dd/plist/ASCIIPropertyListParser.java#L758.

**Actual results:**
`errorOffset` points to an index out of bounds because it adds `ex.getErrorOffset()` (the error offset within the quoted string being parsed) to `this.index` (the end of the quoted string being parsed).

**Comment by 3breadt** [comment]
Thanks for your contribution 😊
