### ISSUE TITLE
Gradle support

### ISSUE THREAD

**Issue by massimobio** [3breadt/dd-plist#9]
I currently use the Google Code Gradle dependency: compile 'com.googlecode.plist:dd-plist:1.16'
Any plans to add Gradle support to these GitHub releases of dd-plist?

**Comment by 3breadt** [comment]
The current release 1.17 has not yet been uploaded to Maven central repository (which can be accessed with Gradle). I did not yet have the time to do so. Once it's up there I will update the README.MD to point to the new release as the one to use.

**Comment by virusman** [comment]
Are there any plans to release it on Maven Central?

**Comment by 3breadt** [comment]
Just done so.
