### ISSUE TITLE
Add location information to NSObject nodes

### ISSUE THREAD

**Issue by HiranChaudhuri** [3breadt/dd-plist#90]
When parsing errors occur there is just a message that something did not work out. For users it is good to know where (filename, line, column). I know it is not always possible, e.g. when some binary plist is loaded via the network as an InputStream.
But in cases where a simple text file is parsed the likelyhood of this being inspected manually is a lot higher.

Would it be possible to add a 'location' field to NSObject that contains as much data as was available when creating it?

**Comment by 3breadt** [comment]
This is not easily done.


The ASCII property list parser is only parser where location information is available. But only the offset within the file, not the line or column number.

**Comment by 3breadt** [comment]
@HiranChaudhuri Please take a look at this pull request #95 and check if that addresses your concerns.

**Comment by 3breadt** [comment]
All requested features should be taken care of by the merged PR #95 .
