### ISSUE TITLE
Add parent relationship to NSObject

### ISSUE THREAD

**Issue by HiranChaudhuri** [3breadt/dd-plist#91]
At runtime, having parsed a plist the result is a hierarchy of NSObject nodes. 
While it is possible to navigate downwards from the root, it is not possible navigating upwards from a leaf.

This could come handy if during processing of the hierarchy a problem is spotted in the 23rd element of a string array. Here it could be meaningful just to be able to navigate back to root and while doing so building up something like a [location path](https://www.w3.org/TR/1999/REC-xpath-19991116/#location-paths).

**Comment by 3breadt** [comment]
In binary property lists there is no guaranteed 1:1 parent-child relationship among NSObjects. For example, if Dictionary A and B both contain the string "foo", it may just be stored once in the binary property list. When parsing the binary property list the NSString object with the content "foo" would then have two parents, Dictionary A and B.

The same is true when using this library to create a property list, the user is free to reuse objects and add them into several NSObjects, NSArrays, etc.

Thus I would not like to have a parent property on the NSObject in this library. Keeping track of where you are can be solved within your own project that uses this API, without needing to integrate it here.
