### ISSUE TITLE
ModiTect configuration missing

### ISSUE THREAD

**Issue by MaxiHuHe04** [3breadt/dd-plist#97]
First of all, thank you very much for this library. A few days ago, I saw the recent update which should have added support for the Java module system. I was happy that the Maven warning in one of my projects that uses it would finally be gone and thought about using jpackage now.
However, it seems that you removed the ModiTect Maven plugin configuration from the PR in the commit 0c61f1fdcc059fbc0f5fc216d456031ff8adef2a. Did it cause any problems or was this just by accident?

**Comment by 3breadt** [comment]
Thanks for bringing that to my attention. The plugin was removed accidentally. I restored it again.
