### ISSUE TITLE
Why can't I use NSObject.wrap()

### ISSUE THREAD

**Issue by mumangguo** [3breadt/dd-plist#99]
jdk:17
dependency:
 <dependency>
          <groupId>com.googlecode.plist</groupId>
          <artifactId>dd-plist</artifactId>
          <version>1.28</version>
      </dependency>
`NSArray objects = new NSArray(28);
        objects.setValue(0, NSObject.wrap(null));`
![image](https://github.com/user-attachments/assets/f28487db-0298-4cfc-9afe-12da27654ef3)

**Comment by 3breadt** [comment]
Because there is no method named `wrap` . All available methods are documented in the [JavaDoc](https://3breadt.github.io/dd-plist/).

No wrapping is needed in your example, just use setValue without wrapping the `null` value.
